### ISSUE TITLE
Support usage of GUI clients

### ISSUE THREAD

**Issue by yozlet** [18F/cf-db-connect#17]
If I need to perform complex work on a remote DB, I'll fire up a graphical client. The good news is that making this work might be as simple as printing out the tunnel details & DB credentials before the DB CLI is started, so that I can enter them into the client connection screen.

I don't think this needs a separate mode or anything. Even though it fires up a CLI which I won't use, it's convenient that closing the tunnel at the end is as easy as quitting the CLI.

**Comment by afeld** [comment]
Aye. Probably just a simple flag like `--skip-connect` to not fire up the corresponding CLI.

**Comment by yozlet** [comment]
So with `--skip-connect`, does the command just sleep with the tunnel open until the user kills it, at which point the tunnel closes? (That's what I'd recommend.)

**Comment by afeld** [comment]
Aye. I just made that flag name up, by the way. `--command none` or `--no-command` are others, to be consistent with the proposal in https://github.com/18F/cf-db-connect/issues/18. Very open to ideas here.

**Comment by mogul** [comment]
Maybe `--no-client`. (You might also consider renaming this to
`cf-service-connect` or something at the point that this is implemented as
it'll be less specifically about DBs and their clients at that point.)
